### ISSUE TITLE
Полеев: "Коллизии с блоками, перемещение персонажа"

### ISSUE THREAD

**Issue by Inconspicuousness** [ge0rge1012/Dark_Project#14]
- [x] Разработка механики работы с блоками в движке

- [x] Работа со скоростью, гравитацией движения

- [x] Улучшение созданных коллизий

- [x] Улучшение перемещения

**Comment by ge0rge1012** [comment]
There is always what to improve, but main bugs are fixed

**Comment by ge0rge1012** [comment]
Everything is done, so now just optimisation and improvement
